

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author alancisneros
 */


import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import java.io.IOException;
import java.net.URL;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.*;


public class Domino extends JFrame {

    
    
    java.util.Timer vueltas;
    Random ramdon=new Random();
    ArrayList fichas=new ArrayList();    
    ArrayList jugadores=new ArrayList();
    int X1,Y1,X2,Y2;
    Jugador j1,j2,j3,j4; 
    int jugadorpos=0;
    Ficha cursor=null;
    Ficha f=null;
    int b1=0,b2=0;
  static public ArrayList fichastodas=new ArrayList();
    
    
   
    public Domino() {
        initComponents();
        
        
        this.setLocationRelativeTo(null);
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        
                
    }
        
        
      
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        area = new javax.swing.JTextArea();
        Tablero = new javax.swing.JPanel();
        panelJugador3 = new javax.swing.JPanel();
        panelJugador1 = new javax.swing.JPanel();
        panelJugador2 = new javax.swing.JPanel();
        panelJugador4 = new javax.swing.JPanel();
        nombreJugador3 = new javax.swing.JLabel();
        nombreJugador1 = new javax.swing.JLabel();
        nombreJugador4 = new javax.swing.JLabel();
        nombreJugador2 = new javax.swing.JLabel();
        foto2 = new javax.swing.JLabel();
        b5 = new javax.swing.JButton();
        foto6 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        foto7 = new javax.swing.JLabel();
        b6 = new javax.swing.JButton();
        foto1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1350, 800));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setMinimumSize(new java.awt.Dimension(200, 800));
        jPanel2.setPreferredSize(new java.awt.Dimension(200, 800));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Empezar Partida");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        area.setColumns(20);
        area.setRows(5);
        jScrollPane1.setViewportView(area);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 190, 720));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 0, 200, 770));

        Tablero.setBackground(new java.awt.Color(255, 255, 204));
        Tablero.setBorder(javax.swing.BorderFactory.createTitledBorder("Bienvenido al juego"));
        Tablero.setPreferredSize(new java.awt.Dimension(1000, 800));
        Tablero.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelJugador3.setPreferredSize(new java.awt.Dimension(280, 80));
        panelJugador3.setLayout(new java.awt.GridLayout(1, 7));
        Tablero.add(panelJugador3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, 280, 80));
        panelJugador3.getAccessibleContext().setAccessibleDescription("");

        panelJugador1.setPreferredSize(new java.awt.Dimension(280, 80));
        panelJugador1.setLayout(new java.awt.GridLayout(1, 7));
        Tablero.add(panelJugador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 650, 280, 80));

        panelJugador2.setPreferredSize(new java.awt.Dimension(80, 280));
        panelJugador2.setLayout(new java.awt.GridLayout(7, 1));
        Tablero.add(panelJugador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 170, 80, 280));

        panelJugador4.setPreferredSize(new java.awt.Dimension(80, 280));
        panelJugador4.setLayout(new java.awt.GridLayout(7, 1));
        Tablero.add(panelJugador4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 80, 280));
        Tablero.add(nombreJugador3, new org.netbeans.lib.awtextra.AbsoluteConstraints(234, 10, 80, 30));
        Tablero.add(nombreJugador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 680, 100, 30));
        Tablero.add(nombreJugador4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 144, 90, 30));
        Tablero.add(nombreJugador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 120, 80, 30));
        Tablero.add(foto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 480, 80, 60));

        b5.setText("Foto");
        b5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5ActionPerformed(evt);
            }
        });
        Tablero.add(b5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 570, -1, -1));
        Tablero.add(foto6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, 100, 50));

        jButton5.setText("Foto");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        Tablero.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 550, -1, -1));
        Tablero.add(foto7, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 20, 100, 50));

        b6.setText("Foto");
        b6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b6ActionPerformed(evt);
            }
        });
        Tablero.add(b6, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 90, -1, -1));
        Tablero.add(foto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 630, 90, 50));

        jButton2.setText("Foto");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        Tablero.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 690, -1, -1));

        getContentPane().add(Tablero, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Tablero.removeAll();
        fichas=new ArrayList();    
        jugadores=new ArrayList();
        area.setText("");
        
        cursor=null;
        f=null;
        b1=0;b2=0;
        j=null;
        fichastodas=new ArrayList();
        
        panelJugador3 = new javax.swing.JPanel();
        panelJugador1 = new javax.swing.JPanel();
        panelJugador2 = new javax.swing.JPanel();
        panelJugador4 = new javax.swing.JPanel();
        nombreJugador3 = new javax.swing.JLabel();
        nombreJugador1 = new javax.swing.JLabel();
        nombreJugador4 = new javax.swing.JLabel();
        nombreJugador2 = new javax.swing.JLabel();
        
        panelJugador3.setPreferredSize(new java.awt.Dimension(280, 80));
        panelJugador3.setLayout(new java.awt.GridLayout(1, 7));
        Tablero.add(panelJugador3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, 280, 80));
        panelJugador3.getAccessibleContext().setAccessibleDescription("");

        panelJugador1.setPreferredSize(new java.awt.Dimension(280, 80));
        panelJugador1.setLayout(new java.awt.GridLayout(1, 7));
        Tablero.add(panelJugador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 650, 280, 80));

        panelJugador2.setPreferredSize(new java.awt.Dimension(80, 280));
        panelJugador2.setLayout(new java.awt.GridLayout(7, 1));
        Tablero.add(panelJugador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 170, 80, 280));

        panelJugador4.setPreferredSize(new java.awt.Dimension(80, 280));
        panelJugador4.setLayout(new java.awt.GridLayout(7, 1));
        Tablero.add(panelJugador4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 80, 280));
        Tablero.add(nombreJugador3, new org.netbeans.lib.awtextra.AbsoluteConstraints(234, 10, 80, 30));
        Tablero.add(nombreJugador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 680, 100, 30));
        Tablero.add(nombreJugador4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 144, 90, 30));
        Tablero.add(nombreJugador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 120, 80, 30));
        
        Tablero.add(foto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500,500,200,200));
        
         Tablero.add(foto6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150,250,200,200));
         
        Tablero.add(foto7, new org.netbeans.lib.awtextra.AbsoluteConstraints(500,50,200,200));
        
        Tablero.add(foto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(950,250,200,200));
        
        Ficha f00=new Ficha(0,0,fichas);
        Ficha f01=new Ficha(0,1,fichas);
        Ficha f02=new Ficha(0,2,fichas);
        Ficha f03=new Ficha(0,3,fichas);
        Ficha f04=new Ficha(0,4,fichas);
        Ficha f05=new Ficha(0,5,fichas);
        Ficha f06=new Ficha(0,6,fichas);
        
        Ficha f11=new Ficha(1,1,fichas);
        Ficha f12=new Ficha(1,2,fichas);
        Ficha f13=new Ficha(1,3,fichas);
        Ficha f14=new Ficha(1,4,fichas);
        Ficha f15=new Ficha(1,5,fichas);
        Ficha f16=new Ficha(1,6,fichas);
        
        Ficha f22=new Ficha(2,2,fichas);
        Ficha f23=new Ficha(2,3,fichas);
        Ficha f24=new Ficha(2,4,fichas);
        Ficha f25=new Ficha(2,5,fichas);
        Ficha f26=new Ficha(2,6,fichas);
        
        Ficha f33=new Ficha(3,3,fichas);
        Ficha f34=new Ficha(3,4,fichas);
        Ficha f35=new Ficha(3,5,fichas);
        Ficha f36=new Ficha(3,6,fichas);
        
        Ficha f44=new Ficha(4,4,fichas);
        Ficha f45=new Ficha(4,5,fichas);
        Ficha f46=new Ficha(4,6,fichas);
        
        Ficha f55=new Ficha(5,5,fichas);
        Ficha f56=new Ficha(5,6,fichas);
        
        Ficha f66=new Ficha(6,6,fichas);
       
        
        panelJugador1.removeAll();
        panelJugador2.removeAll();
        panelJugador3.removeAll();
        panelJugador4.removeAll();
        
       
        vueltas=new java.util.Timer();
        
        ArrayList fichas1=new ArrayList();
        ArrayList fichas2=new ArrayList();
        ArrayList fichas3=new ArrayList();
        ArrayList fichas4=new ArrayList();
        
         while(fichas1.size()<7)
        {Ficha f=(Ficha)fichas.get((int)(ramdon.nextFloat()*fichas.size()));
         if (!fichas1.contains(f)) {fichas1.add(f);fichas.remove(f);Tablero.remove(f);Tablero.validate();}
        }
        for(int i=0;i<fichas1.size();i++)
        {Ficha f=(Ficha)fichas1.get(i);
         if (!f.visible) f.vuelta();
        if (f.horizontal)f.gira();
        panelJugador1.add(f);
        }
         
        
         Nombre n=new Nombre(null,true);
         n.setLocationRelativeTo(null);
         n.humano.setVisible(true);
         n.virtual.setVisible(true);
         n.setVisible(true); 
         
         if(n.humano.isSelected())  j1=new Jugador(fichas1);
         else  j1=new JugadorVirtual2(fichas1);
         
         j1.nombre=n.nombre.getText();
         nombreJugador1.setText(j1.nombre);
        
         
        
       
       
        
         while(fichas2.size()<7)
        {Ficha f=(Ficha)fichas.get((int)(ramdon.nextFloat()*fichas.size()));
         if (!fichas2.contains(f)) {fichas2.add(f);fichas.remove(f);Tablero.remove(f);Tablero.validate();}
        }
         
         for(int i=0;i<fichas2.size();i++)
        {Ficha f=(Ficha)fichas2.get(i);
        if (!f.horizontal)f.gira();
        panelJugador2.add(f);
        }
        
         j2=new JugadorVirtual2(fichas2);
         
         n=new Nombre(null,true);
         n.setLocationRelativeTo(null);
         n.humano.setVisible(false);
         n.virtual.setVisible(false);
         n.setVisible(true); 
         
         j2.nombre=n.nombre.getText();
         
         nombreJugador2.setText(j2.nombre);
        
        while(fichas3.size()<7)
        {Ficha f=(Ficha)fichas.get((int)(ramdon.nextFloat()*fichas.size()));
         if (!fichas3.contains(f)) {fichas3.add(f);fichas.remove(f);Tablero.remove(f);Tablero.validate();}
        }
        
        for(int i=0;i<fichas3.size();i++)
        {Ficha f=(Ficha)fichas3.get(i);
        if (f.horizontal)f.gira();
        panelJugador3.add(f);
        }
         
         j3=new JugadorVirtual2(fichas3);
         n=new Nombre(null,true);
         n.setLocationRelativeTo(null);
         n.humano.setVisible(false);
         n.virtual.setVisible(false);
         n.setVisible(true); 
         j3.nombre=n.nombre.getText();
         
         nombreJugador3.setText(j3.nombre);
        
        while(fichas4.size()<7)
        {Ficha f=(Ficha)fichas.get((int)(ramdon.nextFloat()*fichas.size()));
         if (!fichas4.contains(f)) {fichas4.add(f);fichas.remove(f);Tablero.remove(f);Tablero.validate();}
        }
        
        for(int i=0;i<fichas4.size();i++)
        {Ficha f=(Ficha)fichas4.get(i);
        if (!f.horizontal)f.gira();
        panelJugador4.add(f);
        }
        
         j4=new JugadorVirtual2(fichas4);
         n=new Nombre(null,true);
         n.setLocationRelativeTo(null);
         n.humano.setVisible(false);
         n.virtual.setVisible(false);
         n.setVisible(true); 
         j4.nombre=n.nombre.getText();
         nombreJugador4.setText(j4.nombre);
        
        jugadores.add(j1);
        jugadores.add(j2);
        jugadores.add(j3);
        jugadores.add(j4);
        
       jugadorpos=(int)(jugadores.size()*ramdon.nextFloat());
      
       TimerTask timerTask = new TimerTask() {public void run() {try { vueltas();
                                                               } catch (Exception ex) {ex.printStackTrace();}
                                                            }
                                         };
        
        X2=X1=Tablero.getWidth()/2;
        Y2=Y1=Tablero.getHeight()/2;
        
       
         Tablero.repaint();
        Tablero.validate();
        
         vueltas.scheduleAtFixedRate(timerTask, 0,2000);
        
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        JFileChooser fc = new JFileChooser();
        int seleccion = fc.showOpenDialog(this);
        
        if (seleccion == JFileChooser.APPROVE_OPTION){
       
        
       
        
        rsscalelabel.RSScaleLabel.setScaleLabel(foto1, fc.getSelectedFile().toString());
        
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void b5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5ActionPerformed
         JFileChooser fc = new JFileChooser();
        int seleccion = fc.showOpenDialog(this);
        
        if (seleccion == JFileChooser.APPROVE_OPTION){
       
        
       
        
        rsscalelabel.RSScaleLabel.setScaleLabel(foto6, fc.getSelectedFile().toString());
        
        }
    }//GEN-LAST:event_b5ActionPerformed

    private void b6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b6ActionPerformed
        // TODO add your handling code here:
         JFileChooser fc = new JFileChooser();
        int seleccion = fc.showOpenDialog(this);
        
        if (seleccion == JFileChooser.APPROVE_OPTION){
       
        
       
        
        rsscalelabel.RSScaleLabel.setScaleLabel(foto7, fc.getSelectedFile().toString());
        
        }
    }//GEN-LAST:event_b6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        JFileChooser fc = new JFileChooser();
        int seleccion = fc.showOpenDialog(this);
        
        if (seleccion == JFileChooser.APPROVE_OPTION){
       
        
       
        
        rsscalelabel.RSScaleLabel.setScaleLabel(foto2, fc.getSelectedFile().toString());
        
        }
    }//GEN-LAST:event_jButton5ActionPerformed
    
    Jugador j;
    Random random=new  Random();
    
   
    
    void vueltas(){
     
        j=(Jugador)jugadores.get(jugadorpos);
        jScrollPane1.getVerticalScrollBar().setValue(jScrollPane1.getVerticalScrollBar().getMinimum()); 
        jScrollPane1.repaint(); 
        foto1.setVisible(true);
        
        if (cursor!=null&&(j.LLeva(cursor.e1)||j.LLeva(cursor.e2))) f= j.dameFicha(cursor);  
        
        else if (cursor!=null) {  javax.swing.JOptionPane.showMessageDialog
                                (null,"Paso",((Jugador)jugadores.get(jugadorpos)).nombre+" No tiene fichas para jugar",javax.swing.JOptionPane.OK_OPTION);      
                                   
                                  area.setText(
                                 ((Jugador)jugadores.get(jugadorpos)).nombre+"\n"+
                                 "Paso \n"+
                                 "Paso \n\n"+
                                 area.getText()+"\n"         
                                 );
        
                                  jugadorpos++;
                                  if (jugadorpos==jugadores.size()) jugadorpos=0;
                                  return;
                                      }        
        else if (cursor==null) f= j.dameFicha(cursor);
        
        
        area.setText(
                     "Es el turno de:\n"+
                     j.nombre+"\n\n"+
                    area.getText()+"\n" 
                    );
        
   if(f!=null){
       
        area.setText(
          j.nombre+"\n"+
          "juega "+
          f.e1+":"+f.e2+"\n"+
          area.getText()
         );
                         
        if (cursor==null) {cursor=new Ficha(f.e1,f.e2,fichas);
                           cursor.setVisible(false);
                            
                                                  
                           
                           if (f.esDoble()&&f.horizontal)f.gira();
                           if (!f.esDoble()&&!f.horizontal) f.gira(); 
                           if (f.esDoble())
                                Tablero.add(f, new org.netbeans.lib.awtextra.AbsoluteConstraints(X1,Y1-Ficha.tamaño/2, -1, -1));
                           else Tablero.add(f, new org.netbeans.lib.awtextra.AbsoluteConstraints(X1,Y1, -1, -1));
                           if (!f.visible) f.vuelta();
                           if (!f.esDoble())  X2+=Ficha.tamaño*2;
                           else  X2+=Ficha.tamaño;
                           
                           Tablero.validate();
                           j.fichas.remove(f);
                           
                           
                           
                             }
    else{
              int c1,c2;
             
             
          
     if (cursor.e1==f.punta){
            
                             if (X1>220&&b1==0){ 
                                    if (!f.esDoble())  X1-=Ficha.tamaño*2; 
                                    else X1-=Ficha.tamaño;
                                    if(f.e1==f.punta) {c1=f.e2;}
                                    else {c1=f.e1;}
                                    c2=cursor.e2;
                                    if (f.punta==f.e1) f.invierte();
                                    
                                    
                                    if (f.esDoble()&&f.horizontal)f.gira();
                                    if (!f.esDoble()&&!f.horizontal) f.gira();
                                    if (f.esDoble())
                                         Tablero.add(f, new org.netbeans.lib.awtextra.AbsoluteConstraints(X1,Y1-Ficha.tamaño/2, -1, -1));
                                    else Tablero.add(f, new org.netbeans.lib.awtextra.AbsoluteConstraints(X1,Y1, -1, -1));
                                     
                                      if (!f.visible) f.vuelta();
                                        
                                    Tablero.validate(); 
                                     j.fichas.remove(f);
                                     cursor.e1=c1;
                                     cursor.e2=c2;
                                    }
                             else{b1=1;
                                    if (X1<=220) {Y1=Y1-100;
                                    //X1-=Ficha.tamaño;
                                    }
                                    
                                    
                                    if(f.e1==f.punta) {c1=f.e2;}
                                    else {c1=f.e1;}
                                    c2=cursor.e2;
                                    if (f.punta==f.e2) f.invierte();
                                    if (f.esDoble()&&f.horizontal)f.gira();
                                    if (!f.esDoble()&&!f.horizontal) f.gira();
                                    if(f.esDoble())
                                         Tablero.add(f, new org.netbeans.lib.awtextra.AbsoluteConstraints(X1,Y1-Ficha.tamaño/2, -1, -1));
                                    else Tablero.add(f, new org.netbeans.lib.awtextra.AbsoluteConstraints(X1,Y1, -1, -1));
                                    
                                    if (!f.esDoble()) X1+=Ficha.tamaño*2;
                                    else X1+=Ficha.tamaño;
                                     
                                    if (!f.visible) f.vuelta();
                                    
                                    if(X1>=Tablero.getWidth()-300) {Y1=Y1-100;b1=0;
                                    //X1+=Ficha.tamaño*2;
                                    }
                                        
                                    Tablero.validate(); 
                                     j.fichas.remove(f);
                                     cursor.e1=c1;
                                     cursor.e2=c2;
                                    
                                }
                                    
       }
           
     else if(cursor.e2==f.punta) {
                                if (X2<Tablero.getWidth()-280&&b2==0){
                                    
                                   
                                    
                                    if(f.e1==f.punta) {c2=f.e2;}
                                    else {c2=f.e1;}
                                    c1=cursor.e1;
                                    if (f.punta==f.e2) f.invierte();
                                          
                                     if (f.esDoble()&&f.horizontal)f.gira();
                                     if (!f.esDoble()&&!f.horizontal) f.gira();
                                     if (f.esDoble())
                                          Tablero.add(f, new org.netbeans.lib.awtextra.AbsoluteConstraints(X2,Y2-Ficha.tamaño/2, -1, -1));
                                     else Tablero.add(f, new org.netbeans.lib.awtextra.AbsoluteConstraints(X2,Y2, -1, -1));
                                      
                                      if (!f.esDoble()) X2+=Ficha.tamaño*2;
                                    else X2+=Ficha.tamaño;
                                     
                                       if (!f.visible) f.vuelta();
                                        
                                    Tablero.validate();
                                    j.fichas.remove(f); 
                                    cursor.e1=c1;
                                    cursor.e2=c2;
                                        
                                }
                                else{  b2=1; 
                                       if (X2>=Tablero.getWidth()-300) {Y2=Y2+100;
                                       //X2=X2+Ficha.tamaño;
                                       }
                                 
                                      if (!f.esDoble()) X2-=Ficha.tamaño*2;
                                      else   X2-=Ficha.tamaño;
                                     
                                      
                                       if(f.e1==f.punta) {c2=f.e2;}
                                       else {c2=f.e1;}
                                       c1=cursor.e1;
                                       if (f.punta==f.e1) f.invierte();
                                       if (f.esDoble()&&f.horizontal)f.gira();
                                       if (!f.esDoble()&&!f.horizontal) f.gira();
                                       if (f.esDoble())
                                            Tablero.add(f, new org.netbeans.lib.awtextra.AbsoluteConstraints(X2,Y2-Ficha.tamaño/2, -1, -1));
                                       else Tablero.add(f, new org.netbeans.lib.awtextra.AbsoluteConstraints(X2,Y2, -1, -1));
                                       
                                      
                                        if (!f.visible) f.vuelta();
                                         if(X2<220){Y2=Y2+100;b2=0;
                                         //X2-=Ficha.tamaño*2;
                                         }
                                        
                                      Tablero.validate();
                                      j.fichas.remove(f); 
                                      cursor.e1=c1;
                                      cursor.e2=c2;
                                }
                                      
       }   
    else {javax.swing.JOptionPane.showMessageDialog
                                (null,"Seleccion incorrecta","Esa no",javax.swing.JOptionPane.OK_OPTION);      
                  f.seleccionada=false;
                  
                  area.setText(
                     "No puedes jugar esa ficha,\n"+
                     j.nombre+
                     "No puedes jugar esa ficha.\n\n"+
                     area.getText()+"\n"        
                   );
         return;
         }               
        }
       
        panelJugador1.repaint();
        panelJugador1.setLayout(new java.awt.GridLayout(1,j1.fichas.size(), 0, 0));
        Tablero.add(panelJugador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 650, Ficha.tamaño*j1.fichas.size(), Ficha.tamaño*2));

        panelJugador2.repaint();
        panelJugador2.setLayout(new java.awt.GridLayout(j2.fichas.size(), 1, 0, 0));
        Tablero.add(panelJugador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 170, Ficha.tamaño*2, j2.fichas.size()*Ficha.tamaño));

        panelJugador3.repaint();
        panelJugador3.setLayout(new java.awt.GridLayout(1,j3.fichas.size(), 0, 0));
        Tablero.add(panelJugador3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, Ficha.tamaño*j3.fichas.size(), Ficha.tamaño*2));
        
        panelJugador4.repaint();
        panelJugador4.setLayout(new java.awt.GridLayout(j4.fichas.size(), 1, 0, 0));
        Tablero.add(panelJugador4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, Ficha.tamaño*2,j4.fichas.size()*Ficha.tamaño));
        
       ////////////////////////////////////////////////////////////////////////
        boolean llevaalguien=false; 
        
        
        for(int i=0;i<jugadores.size();i++) 
         {Jugador x=(Jugador)jugadores.get(i);
             if (cursor!=null&&(x.LLeva(cursor.e1)||x.LLeva(cursor.e2))) llevaalguien=true;
         
         }
        
        if (j.fichas.isEmpty())
            
            
                  { for(int i=0;i<jugadores.size();i++)
                       for(int y=0;y<((Jugador)jugadores.get(i)).fichas.size();y++)
                       {Ficha fi=(Ficha)((Jugador)jugadores.get(i)).fichas.get(y);
                       
                         if (!fi.visible) fi.vuelta();
                        
                       }
                      
                      
                      javax.swing.JOptionPane.showMessageDialog
                                (null,"Ha ganado "+j.nombre,"Fin",javax.swing.JOptionPane.OK_OPTION);
       
                     area.setText(
                     "Ha ganado \n"+
                     j.nombre+"\n"+
                     "Fin\n"+
                    area.getText()+"\n"         
                    );
                         
                  
                   vueltas.cancel();
                   Tablero.removeAll();
                  }
        
        else if (!llevaalguien){                          
                           Hashtable tabla=new Hashtable();
                           
                           for(int i=0;i<jugadores.size();i++)
                           {Jugador x=(Jugador)jugadores.get(i);
                            int puntos=0;
                              for(int p=0;p<x.fichas.size();p++)
                               {Ficha fx=(Ficha)x.fichas.get(p);
                               puntos+=fx.e1+fx.e2;
                               }     
                              
                            tabla.put(x,puntos);
                           
                           }
                           
                           int menor=100000;
                           Jugador ganador=null;
                           
                           Enumeration e=tabla.keys();
                            while(e.hasMoreElements())
                            {Jugador r=(Jugador)e.nextElement();
                             if (menor>(int)tabla.get(r)){menor=(int)tabla.get(r);ganador=r;}
                            }
                           
                            e=tabla.keys();
                          
                              for(int i=0;i<jugadores.size();i++)
                       for(int y=0;y<((Jugador)jugadores.get(i)).fichas.size();y++)
                       {Ficha fi=(Ficha)((Jugador)jugadores.get(i)).fichas.get(y);
                       
                         if (!fi.visible) fi.vuelta();
                        
                       }
                            
                            
                            while(e.hasMoreElements())
                           { Jugador z=(Jugador)e.nextElement();
                             int r=(int)tabla.get(z);
                            if (r==menor){  
                                
                                
                                javax.swing.JOptionPane.showMessageDialog
                                (null,"Ha ganado "+z.nombre+"\n"+
                                        "con "+r+" puntos.","Fin",javax.swing.JOptionPane.OK_OPTION);
                                area.setText(
                                "Ha ganado \n"+
                                 z.nombre+"\n"+
                                "con "+r+" puntos. \n"+
                                "Fin.\n"+
                                area.getText()+"\n"        
                                 );
                                          }
                           }
                           
                         
                           
                            vueltas.cancel();
                           Tablero.removeAll();
                          
        
                           }
        
        /////////////////////////////////////////////////////////////////////
        
        
        //////////////////////////////////////////////////////////////////////
        jugadorpos++;           
        if (jugadorpos==jugadores.size()) jugadorpos=0;
            
    
        
        }

}
    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Domino.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Domino.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Domino.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Domino.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Domino().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Tablero;
    private javax.swing.JTextArea area;
    private javax.swing.JButton b5;
    private javax.swing.JButton b6;
    private javax.swing.JLabel foto1;
    private javax.swing.JLabel foto2;
    private javax.swing.JLabel foto6;
    private javax.swing.JLabel foto7;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nombreJugador1;
    private javax.swing.JLabel nombreJugador2;
    private javax.swing.JLabel nombreJugador3;
    private javax.swing.JLabel nombreJugador4;
    private javax.swing.JPanel panelJugador1;
    private javax.swing.JPanel panelJugador2;
    private javax.swing.JPanel panelJugador3;
    private javax.swing.JPanel panelJugador4;
    // End of variables declaration//GEN-END:variables

}
